/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface LoginUserDto {
    username: string;
    password: string;
}

export interface RegisterUserDto {
    username: string;
    password: string;
}

export interface UpdateUserDto {
    username: string;
    password: string;
}

export interface ListPlanDto {
    title: string;
    description: string;
    friendIds: Array<string>;
    isCompleted: boolean;
    planId: string;
}

export interface CreatePlanDto {
    title: string;
    description: string;
    friendIds: Array<string>;
    isCompleted: boolean;
}

export interface UpdatePlanDto {
    title: string;
    description: string;
    friendIds: Array<string>;
    isCompleted: boolean;
    planId: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
