/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Plan controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, CreatePlanDto, UpdatePlanDto } from "../models";

@Injectable({ providedIn: "root" })
export class PlanService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getUserPlanById(planId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getUserPlanById(planId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getUserPlanById(planId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    getUserPlanById(planId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/plans`;

        let params = new HttpParams();
        if (planId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, planId, 'planId');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addPlan(createPlanDto: CreatePlanDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    addPlan(createPlanDto: CreatePlanDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    addPlan(createPlanDto: CreatePlanDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    addPlan(createPlanDto: CreatePlanDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/plans`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createPlanDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateUserPlanById(updatePlanDto: UpdatePlanDto, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updateUserPlanById(updatePlanDto: UpdatePlanDto, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updateUserPlanById(updatePlanDto: UpdatePlanDto, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    updateUserPlanById(updatePlanDto: UpdatePlanDto, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/plans`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updatePlanDto,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteUserPlanById(planId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteUserPlanById(planId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteUserPlanById(planId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteUserPlanById(planId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/plans`;

        let params = new HttpParams();
        if (planId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, planId, 'planId');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getAllByUser(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getAllByUser(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getAllByUser(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    getAllByUser(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/plans/all-by-user`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
